version: 2
jobs:
  build:
    working_directory: /go/src/github.com/shotastage/FileableGo
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run: go get ./...
      - run: go test -v ./...
